protocol: 'https:'
host: 'parsee1053.net'
sitetitle: 'bashcms2ブログ'
sitesubtitle: 'Bootstrapは便利。Pandocも便利。'
links:
- text: '開発日誌(ブログ)'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: 'Twitter'
    href: 'https://twitter.com/parsee1053'
  - text: 'AtCoder'
    href: 'https://atcoder.jp/users/parsee1053'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/parsee1053'
- icon: 'fa-github-square'
  href: 'https://github.com/parsee1053'
- icon: 'fa-linkedin-square'
  href: 'https://www.linkedin.com/in/%E7%BF%94%E5%A4%AA%E9%83%8E-%E5%86%85%E6%9C%A8-57a7a6183/'
hatena: '@'
pocket: '@'
twitter: 'parsee1053'
line: '@'
facebook: '@'
